---

# Use 'latest' to install the latest (stable) release from https://github.com/tus/tusd/releases/, or a valid tag for a
# specific tagged release (e.g. v1.7.3)
tusd_version: latest

# Path of the tusd binary
tusd_path: /usr/local/sbin/tusd

# Owner, group, mode of the tusd binary
# tusd_owner: omit
# tusd_group: omit
# tusd_mode: 0755

# If using Linux, you can install systemd service units to start and manage your tusd instances
tusd_systemd: true

# Configuration for systemd-managed tusd instances - see the README for syntax
tusd_instances: []

# This is used  to download the correct release tarball, which are named like
# 'tusd_{{ tusd_os }}_{{ tusd_arch }}.{{ tusd_archive }}'
tusd_os: "{{ ansible_system | lower }}"
tusd_arch: "{{ (ansible_architecture == 'x86_64') | ternary ('amd64', ansible_architecture) }}"
tusd_archive: "{{ (tusd_os == 'linux') | ternary('tar.gz', 'zip') }}"

# You should generally not set this directly
tusd_binary_platform: "tusd_{{ tusd_os }}_{{ tusd_arch }}"
tusd_binary_archive_url: "https://github.com/tus/tusd/releases/download/{{ tusd_version }}/{{ tusd_binary_platform }}.{{ tusd_archive }}"
