---
galaxy_info:
  author: Akihiro Uchida
  description: ansible role to install miniconda and create conda environment
  license: CC0
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
     - xenial
     - trusty
     - precise
  - name: Debian
    versions:
     - jessie
     - wheezy
  - name: EL
    versions:
      - 7
      - 6
  categories:
  - packaging
dependencies: []
