---

- name: Install nginx (APT)
  apt:
    pkg: nginx-{{ nginx_flavor }}
  notify:
    - restart nginx

- name: Disable default vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx
