---

- name: Include Node.js setup tasks
  include_tasks: nodejs.yml
  when: gie_proxy_setup_nodejs is not none

- name: Install GIE Proxy
  git:
    dest: "{{ gie_proxy_dir }}"
    repo: "{{ gie_proxy_git_repo }}"
    version: "{{ gie_proxy_git_version |default(omit) }}"
  notify:
    - Restart GIE Proxy

- name: Install Node.js modules
  npm:
    path: "{{ gie_proxy_dir }}"
    executable: "{{ gie_proxy_npm_executable |default(omit) }}"
    unsafe_perm: "{{ gie_proxy_npm_unsafe_perm |default(omit) }}"
  environment:
    PATH: "{{ ansible_path |default(ansible_env.PATH) }}"

- name: Include Service setup tasks
  include_tasks: service.yml
  when: gie_proxy_setup_service is not none
