---

- name: Install Node.js (package)
  package:
    name: "{{ gie_proxy_nodejs_package }}"
  when: gie_proxy_setup_nodejs == "package"

- name: Install Node.js (nodeenv) Tasks
  block:

    - name: Install Nodeenv
      pip:
        name: nodeenv
        virtualenv: "{{ gie_proxy_virtualenv }}"
        virtualenv_command: "{{ gie_proxy_virtualenv_command |default(omit) }}"
        virtualenv_python: "{{ gie_proxy_virtualenv_python |default(omit) }}"

    - name: Add virtualenv to $PATH
      set_fact:
        ansible_path: "{{ gie_proxy_virtualenv }}/bin:{{ ansible_env.PATH }}"

    - name: Install Node.js
      command: "nodeenv -p {{ '-n ' ~ gie_proxy_nodejs_version if gie_proxy_nodejs_version is defined else '' }}"
      args:
        creates: "{{ gie_proxy_virtualenv }}/bin/node"
      environment:
        PATH: "{{ ansible_path }}"

  when: gie_proxy_setup_nodejs == "nodeenv"
