---

- name: Manage Paths
  block:

    - name: Deploy Galaxy Unit
      template:
        owner: root
        group: root
        mode: 0644
        src: systemd/galaxy.service.j2
        dest: /etc/systemd/system/galaxy.service
      notify:
        - daemon reload
        - galaxy mule restart

    - name: Enable Galaxy Unit
      systemd:
        name: galaxy.service
        enabled: yes

  remote_user: "{{ galaxy_remote_users.root | default(__galaxy_remote_user) }}"
  become: "{{ true if galaxy_become_users.root is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.root | default(__galaxy_become_user) }}"
