- hosts: [galaxyservers, remoteservers]
  become: true
  become_user: root
  vars_files:
    - group_vars/galaxyservers.yml
    - group_vars/secret.yml
    - group_vars/sdr-secret.yml 
    - group_vars/locations.yml
  vars_prompt:
    - name: username
      prompt: Please enter new user's username
      private: no
    - name: email
      prompt: Please enter new user's email address
      private: no
    - name: password
      prompt: Please enter new user's password (they should change this after first login)
      private: no
  tasks:
    - name: Add the user
      shell: >
        python3 '{{ sdr_install_scripts }}/add-user.py'
        --api-key '{{ master_api_key }}'
        --server 'https://{{ inventory_hostname }}/'
        --new-user-name '{{ username }}'
        --new-user-email '{{ email }}'
        --new-user-password '{{ password }}'
        --tool-path '{{ sdr_workflows }}'
      register: user_api_key
    - name: Print user API key
      debug:
        msg: '{{ user_api_key.stdout }}'
