- hosts: [galaxyservers, remoteservers]
  become: true
  become_user: root
  vars_files:
    - group_vars/galaxyservers.yml
    - group_vars/sdr-secret.yml
    - group_vars/sdr-config.yml
    - group_vars/users.yml
  pre_tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        update_cache: yes
        name: "*"
        state: latest
      tags: packages
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'libbz2-dev', 'liblzma-dev', 'make', 'python3-pip', 'python3-psycopg2', 'tar', 'virtualenv', 'zip' ]
    - pip:
        name: pip
        state: latest
  post_tasks:
    # Perform modifications to fix broken 22.05 deployment
    - name: change /srv/galaxy/var/tmp permissions
      file:
        path: '{{ item }}'
        state: directory
        owner: "{{ owner }}"
        group: "{{ owner }}"
        mode: "{{ mode }}"
        recurse: yes
      loop:
        - "/srv/galaxy/var/tmp"
        - "/srv/galaxy/var/gravity"
    - name: Restart galaxy
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes 
        name: galaxy 
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - geerlingguy.docker
    - galaxyproject.tusd
