- hosts: [galaxyservers, remoteservers]
  become: true
  become_user: root
  vars_files:
    - group_vars/galaxyservers.yml
    - group_vars/sdr-secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'libbz2-dev', 'liblzma-dev', 'make', 'python3-psycopg2', 'tar', 'virtualenv', 'zip' ]
    - pip:
        name: pip
        state: latest
  post_tasks:
    - name: Restart galaxy
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes 
        name: galaxy 
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - geerlingguy.docker
    - galaxyproject.tusd
