- src: galaxyproject.galaxy
  version: 0.10.3
- src: galaxyproject.nginx
  version: 0.7.0
- src: galaxyproject.postgresql
  version: 1.0.3
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.certbot
  version: 0.1.5
- src: galaxyproject.tusd
  version: 0.0.1
- src: geerlingguy.docker
  version: 2.6.0
- src: usegalaxy_eu.gie_proxy
  version: 0.0.2
