---
galaxy_info:
  role_name: nginx
  namespace: galaxyproject
  author: The Galaxy Project
  description: Install and manage an nginx server.
  company: The Galaxy Project
  license: AFL v3.0
  min_ansible_version: 2.7
  github_branch: main
  platforms:
  - name: Ubuntu
    versions:
    - bionic
    - focal
    - groovy
    #- hirsute
  - name: Debian
    versions:
    - jessie
    - stretch
    - buster
    - bullseye
  - name: EL
    versions:
    - 7
    - 8
  - name: SmartOS
    versions:
    - all
    - any
  galaxy_tags:
    - web
dependencies: []
